- name: Add Microsoft APT key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add Microsoft apt repository for MDATP
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64,armhf,amd64] https://packages.microsoft.com/{{ ansible_facts['distribution'] | lower }}/{{ ansible_facts['lsb']['release'] }}/prod {{ ansible_facts['lsb']['codename'] }} main"
    update_cache: true
    state: present
    filename: microsoft-prod.sources
  when: ansible_facts['distribution'] == "Ubuntu"
